img_dirs: [data] 
syms: symb.txt
tr_txt_table: tr.txt
va_txt_table: va.txt
common:
  model_filename: m7
  train_path: EXP
  monitor: va_cer  
logging:
  filepath: train.log
  level: INFO
  to_stderr_level: INFO
  overwrite: true
optimizer:
  learning_rate: 0.0003
  name: RMSProp
data:
  batch_size: 8
train:  
  checkpoint_k: 5
  early_stopping_patience: 20
  delimiters: ['<space>']
  augment_training: true
trainer:
  accelerator: null
  gpus: 1
  weights_summary: full  
